#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: strapi
  name: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: strapi
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      volumes:
      - name: strapi-config
        configMap:
          name: strapi-config
      containers:
      - name: strapi
        image: strapi:latest
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            /usr/local/bin/docker-entrypoint.sh strapi;
            mkdir -p /srv/tmp;
            cp /srv/scripts/strapi_configure.sh /srv/tmp/;
            chmod u+x /srv/tmp/strapi_configure.sh;
            /srv/tmp/strapi_configure.sh;
            strapi develop
        ports:
          - name: http-port
            protocol: TCP
            containerPort: 1337
        livenessProbe:
          httpGet:
            path: /
            port: http-port
          initialDelaySeconds: 300
          periodSeconds: 10
          failureThreshold: 5
        env:
        - name: DATABASE_CLIENT
          valueFrom:
            configMapKeyRef:
              name: strapi-env
              key: DATABASE_CLIENT
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: strapi-env
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: strapi-env
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: strapi-env
              key: DATABASE_NAME
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: strapi-env-secret
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: strapi-env-secret
              key: DATABASE_PASSWORD
        volumeMounts:
          - mountPath: /srv/scripts
            name: strapi-config
        resources: {}
status: {}
