#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql-demo
  name: mysql-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql-demo
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
      - image: mysql:latest
        name: mysql-demo
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: secret
        args:
          - '--default-authentication-plugin=mysql_native_password'
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: mysql-configure
        ports:
          - name: mysql-port
            protocol: TCP
            containerPort: 3306
        resources: {}
      volumes:
      - configMap:
          defaultMode: 420
          name: mysql-configure
        name: mysql-configure
status: {}
