#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: mysql-demo
  name: mysql-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-demo
  serviceName: mysql-demo-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql-demo
    spec:
      containers:
      - image: mysql:latest
        name: mysql-demo
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: secret
        args:
          - '--default-authentication-plugin=mysql_native_password'
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: mysql-configure
          - mountPath: /var/lib/mysql
            name: mysql-demo-vol
        ports:
          - name: mysql-port
            protocol: TCP
            containerPort: 3306
        resources: {}
      volumes:
      - configMap:
          defaultMode: 420
          name: mysql-configure
        name: mysql-configure
  volumeClaimTemplates:
  - metadata:
      name: mysql-demo-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
